
server:
  port: 3111

env: default


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 5000

mybatis:
  mapper-locations: classpath:/dao/*.xml